#!/usr/bin/env python3

import sys
import os.path
import traceback
import hashlib
import urllib.request
import urllib.error
import arrow
import ics
import json

log = lambda *x, **y: print(*x, **y, file=sys.stderr)

CACHE = os.path.expanduser('~/.cache/calendar/{}')
CALENDARS = os.path.expanduser('~/.config/calendar/config')

try:
    os.makedirs(CACHE.format(''))
except:
    pass

with open(CALENDARS, 'r') as fd:
    _calendars = json.load( fd )['calendars']

def _match(it, text):
    for line in it:
        if line == text : break

def _dropalarms(string):
    it = iter(string.splitlines())
    for line in it:
        if line == 'BEGIN:VALARM' : _match(it, 'END:VALARM')
        else: yield line

def dropalarms(string):
    return '\n'.join(_dropalarms(string))

for _calendar in _calendars:

    url = _calendar['url']

    try:

        log('downloading {}'.format(url))

        data = urllib.request.urlopen(url).read()
        # to check that we can parse the data
        text = data.decode()
        # use workaround for nonrfc valarm blocks (see https://github.com/C4ptainCrunch/ics.py/issues/127)
        text = dropalarms(text)
        calendar = ics.Calendar(text)

        h = hashlib.sha1(url.encode()).hexdigest()
        filename = CACHE.format(h)

        log('writing {} to {}'.format(url, filename))

        with open(filename, 'w') as fd:
            fd.write(text)

    except urllib.error.URLError as err:

        log('Error opening url: {}'.format(url))
        log(err)
        traceback.print_tb(err.__traceback__, file=sys.stderr)

    except ics.parse.ParseError as err:

        log('Error parsing file: {}'.format(url))
        log(err)
        traceback.print_tb(err.__traceback__, file=sys.stderr)

    except arrow.parser.ParserError as err:

        log('Error parsing time for {}'.format(url))
        log(err)
        traceback.print_tb(err.__traceback__, file=sys.stderr)

    except FileNotFoundError as err:

        log('Error writing file for {}'.format(url))
        log(err)
        traceback.print_tb(err.__traceback__, file=sys.stderr)

    except Exception as err:

        log('Unknown exception for {}'.format(url))
        log(err)
        traceback.print_tb(err.__traceback__, file=sys.stderr)
